title: My first GitHub Page
author: JoanDoe11
description: > # this means to ignore newlines until "baseurl:"
  First GitHub page as a product in learning via GitLab.

# social links

github_username:  JoanDoe11

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
